language: python
python: 
  - "3.9"

branches:
  only:
  - main

# env:
#   - GITHUB_TOKEN: $secrets.GITHUB_TOKEN

jobs:
  include:
    - stage: build and deploy pages
      install:
        - pip install quarto-cli
#      script:
#        - quarto render
      script: 
        - quarto publish gh-pages --no-prompt --no-browser --token $GITHUB_TOKEN

stages:
  - build and deploy pages
