language: python
python: 
  - "3.9"

branches:
  only:
  - main

jobs:
  include:
    - stage: build and deploy pages
      install:
        - pip install quarto-cli
      script:
        - quarto render --output-dir build
#      script: 
#        - quarto publish gh-pages --no-prompt --no-browser
      deploy:
      - provider: pages
        github_url: github.ibm.com
        github_token: $GITHUB_TOKEN
        target_branch: gh-pages
        skip_cleanup: true
        local_dir: build
        on:
          branch: main

stages:
  - build and deploy pages
