project:
  type: website
  output-dir: docs

website:
  title: "Quarto-Sample"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    background: black
    left: 
      <div class ="listitem"><a href="https://ibm.com" rel="noopener noreferrer" class="footerLogo"><img src="https://www.ibm.com/brand/experience-guides/developer/8f4e3cc2b5d52354a6d43c8edba1e3c9/02_8-bar-reverse.svg" alt="IBM Logo" class="footer__logo themedComponent_node_modules-@docusaurus-theme-common-lib-components-ThemedComponent-styles-module themedComponent--light_node_modules-@docusaurus-theme-common-lib-components-ThemedComponent-styles-module" width="200" height="200"></a></div>
      <div class="listitem"><a autoid="IBM Client Engineering" href="https://www.ibm.com/client-engineering?mhsrc=ibmsearch_a&mhq=client%20engineering" role="listitem" size=""><!--?lit$182463756$-->IBM Client Engineering</a></div>    
    center: 
          <div class="listitem"><a autoid="Contact IBM" href="https://www.ibm.com/contact?lnk=flg-cont-usen" role="listitem" size=""><!--?lit$182463756$-->Contact IBM</a></div>
          <div class="listitem"><a autoid="Privacy" href="https://www.ibm.com/us-en/privacy" role="listitem" size=""><!--?lit$182463756$-->Privacy</a></div>
          <div class="listitem"><a autoid="Terms of use" href="https://www.ibm.com/legal?lnk=flg-tous-usen" role="listitem" size=""><!--?lit$182463756$-->Terms of use</a></div>
          <div class="listitem"><a autoid="Accessibility" href="https://www.ibm.com/able/?lnk=flg-acce-usen" role="listitem" size=""><!--?lit$182463756$-->Accessibility</a></div>
    right:
       <div class="listitem"><a autoid="IBM Client Engineering" href="https://www.ibm.com/client-engineering?mhsrc=ibmsearch_a&mhq=client%20engineering" role="listitem" size=""><!--?lit$182463756$-->Legal</a></div>
       <div class ="listitem">Sed elementum convallis quam, sed tempor massa dictum sit amet. Phasellus ultricies ante id massa scelerisque interdum. Vestibulum vitae volutpat felis. Sed metus magna, malesuada vitae odio eu, volutpat aliquam odio. Mauris eget purus ex. Praesent nec gravida lorem. Nam rhoncus bibendum nulla at viverra. </div>   

format:
  html:
    theme: custom.scss
    toc: true



